### ISSUE TITLE
Hot reaload issue

### ISSUE THREAD

**Issue by liugangnhm** [ionicfirebaseapp/getflutter#101]
**Describe the bug**

when i use following code ,hot reload not work, button text not change when `model.reading` has been changed

```dart
GFButton(
                    child: model.reading ? Text('Stop') : Text('Continuous'),
                    onPressed: () async {
                      if (!model.reading) {
                        await model.startInventory();
                      } else {
                        await model.stopInventory();
                      }
                    },
                  ),
```

i must set a key for that to work

```dart
GFButton(
                    key: ValueKey(model.reading),
                    //text: model.reading ? 'Stop' : 'Continuous',
                    child: model.reading ? Text('Stop') : Text('Continuous'),
                    onPressed: () async {
                      if (!model.reading) {
                        await model.startInventory();
                      } else {
                        await model.stopInventory();
                      }
                    },
                  ),
```

is that expected?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sandipkakadiya** [comment]
Hi liugangnhm.


Thanks for submitting issue.
We are looking at the issue we will release new version with the fix ASAP possible.

**Comment by Sandipkakadiya** [comment]
New version has been released. it includes fixes of hot reload issue mentioned above.
Please use version `getflutter: ^1.0.8` or above.

**Comment by liugangnhm** [comment]
thanks. this issue seems to be  fixed  but getting another hot reload issue . I will close this issue and open a new one!
