### ISSUE TITLE
Can  we  add some  layou  like  bootstrap

### ISSUE THREAD

**Issue by 986244073** [ionicfirebaseapp/getflutter#107]
the  same  as  title

**Comment by Sandipkakadiya** [comment]
We are working hard to bring all type of possible layouts that user can use for their development.

If you find any issue with GetFlutter please create issue here with flutter and getflutter version and other info with steps to reproduce error.

For requesting/checking on new feature/component that we will be working/releasing next. you can check our [Roadmap](https://roadmap.getflutter.dev/)
