### ISSUE TITLE
undefined name GFType of the button

### ISSUE THREAD

**Issue by 986244073** [ionicfirebaseapp/getflutter#108]
import 'package:getflutter/getflutter.dart';

  GFButton(
                onPressed: (){},
                text: "primary",
                type: GFType.solid,
              ),

undefined name GFType

**Comment by Sandipkakadiya** [comment]
We are working on doc update `https://docs.getflutter.dev`.  we need to change GFType to GTButton. 

so please instead of using `GFType.solid` use `GFButtonType.solid`

**Comment by 986244073** [comment]
thankyou

**Comment by 986244073** [comment]
Our documents need to be updated
