### ISSUE TITLE
GFItemsCarousel height of tiles is wrong

### ISSUE THREAD

**Issue by degloff** [ionicfirebaseapp/getflutter#120]
The way the height of a items container of GFItemsCarousel is calculated does not make sense at all and prevents users from creating thin carousels. In the code the height is set to `size` but this is related to the width of the item container. Do I miss something? 

Here size is set to account for the width of the items container. 

https://github.com/ionicfirebaseapp/getflutter/blob/75ca1fbe26169362d5c5ee207a9e503b208b02d3/lib/components/carousel/gf_items_carousel.dart#L88

```
  @override
  void initState() {
    offset = 0;
    animationController = AnimationController(
      duration: const Duration(milliseconds: dragAnimationDuration),
      vsync: this,
    );
    Future.delayed(Duration.zero, () {
      setState(() {
        final double localWidth = MediaQuery.of(context).size.width;
        width = localWidth;
        size = width / widget.rowCount;
      });
    });
    super.initState();
  }
```

But then in the build function:

https://github.com/ionicfirebaseapp/getflutter/blob/75ca1fbe26169362d5c5ee207a9e503b208b02d3/lib/components/carousel/gf_items_carousel.dart#L183

```
  Widget build(BuildContext context) => GestureDetector(
        onHorizontalDragStart: onSlideStart,
        onHorizontalDragUpdate: onSlide,
        onHorizontalDragEnd: onSlideEnd,
        child: Container(
          width: double.infinity,
          height: size,
          child: Stack(
            children: [
              Positioned(
                left: offset,
                child: Row(
                  children: widget.children
                      .map((child) => Container(
                            width: size,
                            height: size,
                            child: child,
                          ))
                      .toList(),
                ),
              ),
            ],
          ),
        ),
      );
```

**Comment by degloff** [comment]
Should width and height be swapped in https://github.com/ionicfirebaseapp/getflutter/blob/75ca1fbe26169362d5c5ee207a9e503b208b02d3/lib/components/carousel/gf_items_carousel.dart#L183 ?

**Comment by deepikahr** [comment]
Resolved on new version. please update package to the latest version.

current working version is
getflutter: ^1.0.11

**Comment by PietechSolution** [comment]
@degloff we closing issue , if you find any problem open again.
