### ISSUE TITLE
 GFListTIle does not use properly padding, it is hardcoded.

### ISSUE THREAD

**Issue by degloff** [ionicfirebaseapp/getflutter#121]
https://github.com/ionicfirebaseapp/getflutter/blob/75ca1fbe26169362d5c5ee207a9e503b208b02d3/lib/components/list_tile/gf_list_tile.dart#L49

**Comment by Sandipkakadiya** [comment]
Resolved on new version. please update package to the latest version.

current working version is 
`getflutter: ^1.0.11`
