### ISSUE TITLE
GFAccordion the title should be a widget

### ISSUE THREAD

**Issue by zkmark** [ionicfirebaseapp/getflutter#124]
**Is your feature request related to a problem? Please describe.**

When I want to add an icon or an image to the beginning of the title, I can't

**Describe the solution you'd like**
Instead of the title property being string, it is of type Widget

**Describe alternatives you've considered**
 the title should be a widget

**Additional context**

![gfacordeon](https://user-images.githubusercontent.com/10190162/77026995-a9810700-695a-11ea-82a4-18a991a3ed38.png)

**Comment by Sandipkakadiya** [comment]
We already have that option you can use either `title` which let's you pass only string.  or you can use `titleChild ` which lets you pass any widget. but remember title will get priority over titleChild
so if you will have both title will dispaly.
