### ISSUE TITLE
XD UI Kit

### ISSUE THREAD

**Issue by eashanui** [ionicfirebaseapp/getflutter#129]
Hello, friends,
Are there any "Get Flutter" UI kits available for adobe XD?

**Comment by PietechSolution** [comment]
Yes , we have soon will share in docs.

**Comment by eashanui** [comment]
@PietechSolution Thank you!

**Comment by PietechSolution** [comment]
@eashanui You can access the XD link now on our docs. 

http://docs.getflutter.dev/
