### ISSUE TITLE
Can use it but has import bugs

### ISSUE THREAD

**Issue by pyae-sone-phyo** [ionicfirebaseapp/getflutter#59]
**I can use this but it has some bugs when import package in dart  file**

Steps the installation are:
1. Import  'getflutter: ^1.0.0' in pubspec.yaml
2. Run  'flutter pub get' in terminal
3. Import  'package:getflutter/getflutter.dart' in dart file
4. I got this bugs but I can use gf_avater

**Screenshots**
<img width="909" alt="Screenshot 2020-01-23 at 1 29 20 PM" src="https://user-images.githubusercontent.com/46741884/72963069-a3502d80-3de4-11ea-8bb5-3fa1a39de449.png">

**Comment by Sandipkakadiya** [comment]
looks like cache issue.

please clean cache once and try again.
`flutter clean`

to explore more visit this repository. we have demonstareted majority of our plugin in this.
[GetFlutter App Github](https://github.com/ionicfirebaseapp/getflutter-app-kit) we have also released app to playstore [GetFlutter App Playstore](https://play.google.com/store/apps/details?id=dev.getflutter.appkit)

be aware that you have to import specific file to use a particular component.  we will be releasing
`getflutter: ^1.0.2`, By end of the day.  Once released you can use all the  components by single import.
`import 'package:getflutter/getflutter.dart';`

**Comment by pyae-sone-phyo** [comment]
**Yes,I got it, sorry for your time. Have a great success.**
 **Thanks**
