### ISSUE TITLE
Flutter web support?

### ISSUE THREAD

**Issue by jasonlaw** [ionicfirebaseapp/getflutter#91]
Is this going to be 100% compatible with flutter web?

**Comment by PietechSolution** [comment]
Yes, All the widgets are compatible with web too. We are releasing our web Demo version next week.

**Comment by PietechSolution** [comment]
You can keep monitoring this Repo 

https://github.com/ionicfirebaseapp/getflutter-web-kit

We will deploy this version soon.

**Comment by jasonlaw** [comment]
> You can keep monitoring this Repo
> 
> https://github.com/ionicfirebaseapp/getflutter-web-kit
> 
> We will deploy this version soon.

Sure will do, thank you very much!
